name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-${{ matrix.target }}
      - uses: jdx/mise-action@v2
      - run: cargo build
      - run: cargo test
      - run: mise lint
